//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.30 at 01:11:11 AM WEST 
//


package comptes.jax.ws.web.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;


/**
 * <p>Java class for compte complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="compte">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="montant" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compte", propOrder = {
        "code",
        "montant"
})
public class Compte {
    public Compte(Long code, double montant, Date dateCreation) {
        this.dateCreation = dateCreation;
        this.code = code;
        this.montant = montant;
    }

    public Compte() {
    }
    @XmlTransient
    protected Date dateCreation;
    protected Long code;
    protected double montant;

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setCode(Long value) {
        this.code = value;
    }

    /**
     * Gets the value of the montant property.
     */
    public double getMontant() {
        return montant;
    }

    /**
     * Sets the value of the montant property.
     */
    public void setMontant(double value) {
        this.montant = value;
    }

}
