//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.30 at 01:11:11 AM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.web.ws.jax.com/")
package comptes.jax.ws.web.service;
